### PR TITLE
fixed kobuki_description

### PR DESCRIPTION
**Pull request by wng-coder**
I have fixed the kobuki_description and tested it on  Ubuntu amd64 and arm64. I hope that this will be useful for visualization as well as Gazebo simulation.

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
Thanks for the contribution!

This generally looks good to me.  When I ran the tests for this, I saw some warnings that I ended up fixing.

The tests are showing one more warning, which is a missing copyright header on `robot_description.launch.py`.  If you could add one there (BSD license is what the rest of this package uses; https://github.com/kobuki-base/kobuki_ros/blob/devel/kobuki_safety_controller/launch/safety_controller-composed-launch.py is an example), then we can go ahead and merge this.

**Comment by wng-coder** [comment]
Yes, I prefer to add the BSD license to `robot_description.launch.py`. By the way, could please do this for me in the merging step?

**Comment by clalancette** [comment]
> Yes, I prefer to add the BSD license to `robot_description.launch.py`. By the way, could please do this for me in the merging step?

I'd prefer if you did it.  That way there is no question of who added the license later on.  You can just copy the header from https://github.com/kobuki-base/kobuki_ros/blob/devel/kobuki_safety_controller/launch/safety_controller-composed-launch.py , change the Copyright line to your name, and that should be enough to pass the linters.

**Comment by wng-coder** [comment]
@clalancette I have already added the license and pushed it into my repos. Could you proceed ahead?

**Comment by wng-coder** [comment]
@clalancette In addition, I also added the same license to `kobuki_auto_docking/launch/compact.launch.py`.

**Review by clalancette — APPROVED** [review]
This looks good, thanks for iterating!

**Pull request merged**
